# Generated by Django 4.1.5 on 2023-04-20 07:48

from django.db import migrations, models
import uploads.settings


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunkedupload",
            name="file",
            field=models.FileField(
                max_length=255, upload_to=uploads.settings.default_upload_to
            ),
        ),
    ]
